package com.nabto.edge.iamUtil;

public enum IamError {
    BLOCKED_BY_DEVICE_CONFIGURATION,
    INITIAL_USER_ALREADY_PAIRED,
    USER_DOES_NOT_EXIST,
    ROLE_DOES_NOT_EXIST,
    USERNAME_EXISTS,
    INVALID_INPUT,
    PAIRING_MODE_DISABLED,
    IAM_NOT_SUPPORTED,
    AUTHENTICATION_ERROR,
    FAILED
}
